server:
  port: 7676


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      name: config
      profile: test # 读取后缀名称
      uri: http://localhost:8888

#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
