spring:
  application:
    name: consumer-service
server:
  port: 8585
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #可以配置多个Eureka一般在生产环境中会有多个eureka
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

