hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"
server:
  port: 9090
spring:
  application:
    name: service-h1
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        #"*"代表开启所有端点



