hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"
server:
  port: 9987
spring:
  application:
    name: hystrix2
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        #"*"代表开启所有端点
