server:
  port: 8888


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/QKM-0203/Spring-cloud-config.git
          # 搜索目录
          search-paths:
            - Spring-cloud-config
          # 读取分支
      label: master


