server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://www.qkm.com:8788/eureka,http://www.QKM.com:8761/eureka
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          skip-ssl-validation: true
          uri: http://github.com/QKM-0203/Spring-cloud-config.git
          # 搜索目录
          # 读取分支
          username: QKM-0203
          password: 13468724917qkm,
      label: master


